=== trishala111/Gift-Card-Store/Gift Card Store/catalog_20049085.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="GiftCardStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="StoreHeader" />
                <xs:element ref="StoreIntroduction" />
                <xs:element ref="StoreImage" />
                <xs:element ref="GiftCards" />
                <xs:element ref="Conclusion" />
                <xs:element ref="footer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="StoreHeader">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Logo" />
                <xs:element ref="Navbar" />
                <xs:element ref="UserCredentials" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Logo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="LogoContent"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="LogoContent" type="xs:string" />

    <xs:element name="Navbar">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="NavElement" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="NavElement" type="xs:string"></xs:element>

    <xs:element name="UserCredentials">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="UserCredential" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UserCredential" type="xs:string" />

    <xs:element name="StoreIntroduction">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SearchList"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="SearchList">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="search" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="search" />

    <xs:element name="StoreImage">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="StoreTitle" />
                <xs:element ref="StoreSubTitle" />
                <xs:element ref="StoreDetails" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="StoreTitle" type="xs:string" />
    <xs:element name="StoreSubTitle" type="xs:string" />

    <xs:element name="StoreDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="StoreElement" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="StoreElement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ElementImg" />
                <xs:element ref="ElementName" />
                <xs:element ref="ElementDescription" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ElementImg">
        <xs:complexType>
            <xs:attribute ref="id" />
        </xs:complexType>
    </xs:element>

    <xs:element name="ElementName" type="xs:string" />

    <xs:element name="ElementDescription" type="xs:string" />

    <xs:element name="GiftCards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GiftCard" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GiftCard">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CardImage" />
                <xs:element ref="CardAttributes" />
            </xs:sequence>
            <xs:attribute ref="cardID" />
        </xs:complexType>
    </xs:element>

    <xs:element name="CardImage">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CardPicture" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CardPicture">
        <xs:complexType>
            <xs:attribute ref="id"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="cardID" type="xs:ID" />
    <xs:attribute name="id" type="xs:string" />

    <xs:element name="CardAttributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CardName" />
                <xs:element ref="Price" />
                <xs:element ref="StartingDate" />
                <xs:element ref="ValidTill" />
                <xs:element ref="Company" />
                <xs:element ref="Region" />
                <xs:element ref="NumberOfCards" />
                <xs:element ref="NumberOfUser" />
                <xs:element ref="Customizable" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CardName">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="label" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="label" type="xs:string" />

    <xs:element name="Price">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="actualCost" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="actualCost" type="xs:decimal" />

    <xs:element name="StartingDate" type="xs:date" />

    <xs:element name="ValidTill">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="extendable" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="extendable">
        <xs:simpleType>
            <xs:restriction base="xs:boolean" />
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Company">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="store" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="store">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Retail" />
                <xs:enumeration value="Online" />
                <xs:enumeration value="Wholesale" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Region">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Global" />
                <xs:enumeration value="America" />
                <xs:enumeration value="EU" />
                <xs:enumeration value="Australia" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="NumberOfCards">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="120" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="NumberOfUser">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="numberofSharers" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="numberofSharers">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:maxInclusive value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Customizable" type="xs:boolean" />

    <xs:element name="Conclusion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ConclusionTitle" />
                <xs:element ref="ConclusionImages" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ConclusionTitle" type="xs:string" />

    <xs:element name="ConclusionImages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Images" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Images">
        <xs:complexType>
            <xs:attribute ref="id" />
        </xs:complexType>
    </xs:element>

    <xs:element name="footer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footerelements" />
                <xs:element ref="footerelementing" maxOccurs="unbounded" />
                <xs:element ref="footerlanguages" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="footerelements">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footertitle" />
                <xs:element ref="footerelementings" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="footertitle" type="xs:string" />

    <xs:element name="footerelementings" type="xs:string" />

    <xs:element name="footerelementing">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footertitle" />
                <xs:element ref="footerelement" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="footerelement">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="footericon" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="footericon">
        <xs:complexType>
            <xs:attribute ref="id" />
        </xs:complexType>
    </xs:element>

    <xs:element name="footerlanguages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="footerlanugage" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="footerlanugage" type="xs:string" />


</xs:schema>

=== trishala111/Gift-Card-Store/Gift Card Store/catalog_20049085.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="catalog_20049085.css" type="text/css"?>
<GiftCardStore xsi:noNamespaceSchemaLocation="catalog_20049085.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <StoreHeader>
        <Logo>
            <LogoContent/>
        </Logo>
        <Navbar>
            <NavElement>Home</NavElement>
            <NavElement>EGifts</NavElement>
            <NavElement>Brand</NavElement>
            <NavElement>Wishlist</NavElement>
            <NavElement>Contacts</NavElement>
        </Navbar>
        <UserCredentials>
            <UserCredential>Log-In</UserCredential>
            <UserCredential>Sign-Up</UserCredential>
        </UserCredentials>
    </StoreHeader>

    <StoreIntroduction>
        <SearchList>
            Search for Gift Cards
            <search />
        </SearchList>
    </StoreIntroduction>


    <StoreImage>
        <StoreTitle>Send a gift Card</StoreTitle>
        <StoreSubTitle>In three simple steps</StoreSubTitle>
        <StoreDetails>
            <StoreElement>
                <ElementImg id="select" />
                <ElementName>Select a Card</ElementName>
                <ElementDescription>Choose one or more gift cards from our range, along wit the value you wish to load.</ElementDescription>
            </StoreElement>
            <StoreElement>
                <ElementImg id="send" />
                <ElementName>Gift a Card</ElementName>
                <ElementDescription>Enter your delivery details with personal messages to your loved ones.</ElementDescription>
            </StoreElement>
            <StoreElement>
                <ElementImg id="enjoy" />
                <ElementName>Spread Love</ElementName>
                <ElementDescription>Then its time for your lucky recipient to decide where and what to spend on, endlessly.</ElementDescription>
            </StoreElement>
        </StoreDetails>
    </StoreImage>

    <GiftCards>

        <GiftCard cardID="GC-01">
            <CardImage>
                <CardPicture id="Amazon" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Amazon</CardName>
                <Price actualCost="52.5">50</Price>
                <StartingDate>2022-01-20</StartingDate>
                <ValidTill extendable="true">Upto 2 year</ValidTill>
                <Company store="Retail">Multinational</Company>
                <Region>Global</Region>
                <NumberOfCards>125</NumberOfCards>
                <NumberOfUser numberofSharers="3">5</NumberOfUser>
                <Customizable>false</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-02">
            <CardImage>
                <CardPicture id="Apple" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Apple</CardName>
                <Price actualCost="100.50">100</Price>
                <StartingDate>2022-10-10</StartingDate>
                <ValidTill extendable="true">Upto 2 year</ValidTill>
                <Company store="Retail">Multinational</Company>
                <Region>America</Region>
                <NumberOfCards>150</NumberOfCards>
                <NumberOfUser numberofSharers="3">50</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-03">
            <CardImage>
                <CardPicture id="Netflix" />
            </CardImage>
            <CardAttributes>
                <CardName label="Apple">Netflix</CardName>
                <Price actualCost="52.50">30</Price>
                <StartingDate>2022-01-20</StartingDate>
                <ValidTill extendable="true">Upto 1 year</ValidTill>
                <Company store="Retail">Entertaintment Services</Company>
                <Region>Global</Region>
                <NumberOfCards>120</NumberOfCards>
                <NumberOfUser numberofSharers="3">5</NumberOfUser>
                <Customizable>false</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-04">
            <CardImage>
                <CardPicture id="Nike" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Nike</CardName>
                <Price actualCost="52.50">250</Price>
                <StartingDate>2022-10-20</StartingDate>
                <ValidTill extendable="true">Upto 2 year</ValidTill>
                <Company store="Retail">Athletic Apparel</Company>
                <Region>Australia</Region>
                <NumberOfCards>200</NumberOfCards>
                <NumberOfUser numberofSharers="3">50</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-05">
            <CardImage>
                <CardPicture id="PUBG" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">PUBG</CardName>
                <Price actualCost="52.50">150</Price>
                <StartingDate>2022-03-10</StartingDate>
                <ValidTill extendable="true">Upto 1 year</ValidTill>
                <Company store="Retail">Online game</Company>
                <Region>America</Region>
                <NumberOfCards>500</NumberOfCards>
                <NumberOfUser numberofSharers="3">100</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-06">
            <CardImage>
                <CardPicture id="Spotify" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Spotify</CardName>
                <Price actualCost="52.50">60</Price>
                <StartingDate>2022-02-28</StartingDate>
                <ValidTill extendable="true">Upto 6 months</ValidTill>
                <Company store="Retail">Music Streaming</Company>
                <Region>Global</Region>
                <NumberOfCards>200</NumberOfCards>
                <NumberOfUser numberofSharers="3">150</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-07">
            <CardImage>
                <CardPicture id="Sephora" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Sephora</CardName>
                <Price actualCost="52.50">100</Price>
                <StartingDate>2022-12-20</StartingDate>
                <ValidTill extendable="true">Upto 3 months</ValidTill>
                <Company store="Retail">French Multinational</Company>
                <Region>Global</Region>
                <NumberOfCards>200</NumberOfCards>
                <NumberOfUser numberofSharers="3">100</NumberOfUser>
                <Customizable>false</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-08">
            <CardImage>
                <CardPicture id="VictoriasSecret" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Victorias Secret</CardName>
                <Price actualCost="52.50">100</Price>
                <StartingDate>2022-01-25</StartingDate>
                <ValidTill extendable="true">Upto 6 months</ValidTill>
                <Company store="Retail">American Beauty</Company>
                <Region>Global</Region>
                <NumberOfCards>125</NumberOfCards>
                <NumberOfUser numberofSharers="3">10</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-09">
            <CardImage>
                <CardPicture id="ULTABeauty" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">ULTA BEAUTY</CardName>
                <Price actualCost="52.50">50</Price>
                <StartingDate>2022-02-25</StartingDate>
                <ValidTill extendable="true">Upto 1 year</ValidTill>
                <Company store="Retail">Beauty Retailer</Company>
                <Region>Australia</Region>
                <NumberOfCards>130</NumberOfCards>
                <NumberOfUser numberofSharers="3">50</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-10">
            <CardImage>
                <CardPicture id="HappyBirthday" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Happy Birthday</CardName>
                <Price actualCost="52.50">50</Price>
                <StartingDate>2022-03-05</StartingDate>
                <ValidTill extendable="true">Upto 2 years</ValidTill>
                <Company store="Retail">HBD</Company>
                <Region>Global</Region>
                <NumberOfCards>200</NumberOfCards>
                <NumberOfUser numberofSharers="3">50</NumberOfUser>
                <Customizable>true</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-11">
            <CardImage>
                <CardPicture id="PlayStation" />
            </CardImage>
            <CardAttributes>
                <CardName label="AMZN">Play Station</CardName>
                <Price actualCost="52.50">50</Price>
                <StartingDate>2022-02-08</StartingDate>
                <ValidTill extendable="true">Upto 3 years</ValidTill>
                <Company store="Retail">Sony Interactive</Company>
                <Region>Global</Region>
                <NumberOfCards>250</NumberOfCards>
                <NumberOfUser numberofSharers="3">100</NumberOfUser>
                <Customizable>false</Customizable>
            </CardAttributes>
        </GiftCard>

        <GiftCard cardID="GC-12">
            <CardImage>
